version: '3'
services:
  mongosrv:
    image: docker.io/library/mongo:4.4.16
    networks:
      - rede
    deploy:
      resources:
        limits:
          memory: 350M
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=cartoes
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", 'db.runCommand("ping").ok', "|", "mongo", "localhost:27017/cartoes", "--quiet" ]
      interval: 30s
      timeout: 10s
      retries: 3

  mongoweb:
    image: docker.io/library/mongo-express:1.0.0-alpha
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - rede
    ports:
      - "7071:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongosrv
      - ME_CONFIG_MONGODB_PORT=27017
      #- ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_BASICAUTH_USERNAME=mongoexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mongoexpress
    links:
      - mongosrv
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=3", "--spider", "http://mongoexpress:mongoexpress@mongoweb:8081  || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongosrv

  #centralizacao de logs
  elasticsrv:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - rede
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: on-failure
    environment:
      - cluster.name=elastic-cluster
      - discovery.type=single-node
      - http.host=0.0.0.0
      - xpack.monitoring.enabled=true
      - xpack.security.enabled=false
    volumes:
      - elastic:/usr/share/elasticsearch/data

  #Visualizacao dos logs centralizados    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.7
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - rede
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsrv:9200
    depends_on:
      - elasticsrv
  
  #Coletor de traces e exibicao na UI
  zipkinsrv:
    image: docker.io/openzipkin/zipkin:2.24.0
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - rede
    links:
      - elasticsrv
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsrv:9200
    ports:
      - "9411:9411"
    depends_on:
      - elasticsrv
    restart: on-failure
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9411/health  || exit 1" ]
      interval: 10s
      retries: 3

  zipkindep:
    image: docker.io/openzipkin/zipkin-dependencies
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - rede
    links:
      - elasticsrv
      - zipkinsrv
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsrv:9200
      - ES_NODES_WAN_ONLY=true
    depends_on:
      - elasticsrv
      - zipkinsrv

  #microservicos de infra
  eurekasrv:
    build: infra/discovery
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - rede
    ports:
      - "8761:8761"

  gateway:
    build: infra/gateway
    depends_on:
      - eurekasrv
    deploy:
      resources:
        limits:
          memory: 350M
    networks:
      - rede
    ports:
      - "8060:8060"

  #microservicos de negocio
  contasrv:
    build: microsvc/conta
    depends_on:
      - eurekasrv
      - gateway
      - mongosrv
      - zipkinsrv
    deploy:
      resources:
        limits:
          memory: 350M
    networks:
      - rede
    ports:
      - "8061:8061"

  transacaosrv:
    build: microsvc/transacao
    depends_on:
      - eurekasrv
      - gateway
      - mongosrv
      - zipkinsrv
    deploy:
      resources:
        limits:
          memory: 350M
    networks:
      - rede
    ports:
      - "8062:8062"

networks:
  rede:

volumes:
  mongodata:
  elastic:
