server:
  port: 8060

spring:
  application:
    name: gateway

  config:
    import: routes.yaml

  zipkin:
    sender:
      type: web
    baseUrl: http://zipkinsrv:9411/

  sleuth:
    sampler:
      probability: 1.0

ribbon:
  eureka:
    enabled: true

logging:
  file:
    name: '/mylogs/gateway_elk.log'
  level:
    root: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE
    org.pismo.infra: TRACE

eureka:
  instance:
    preferIpAddress: true
    hostname: gateway
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekasrv:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"