spring:
  config:
    activate:
      on-profile: local

  zipkin:
    enabled: false

  sleuth:
    sampler:
      probability: 0

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: cartoes

ribbon:
  eureka:
    enabled: false

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  file: logs/gateway_elk.log