spring:
  cloud.gateway.routes:
    - id: conta-svc
      uri: lb://contasvc
      predicates:
        - Path=/v1/microconta/**
      filters:
        - RewritePath=/v1/microconta/(?<segment>.*), /contamsvc/v1/$\{segment}

    - id: transaction-svc
      uri: lb://transactionsvc
      predicates:
      - Path=/v1/microtransaction/**
      filters:
      - RewritePath=/v1/microtransaction/(?<segment>.*), /transacaomsvc/v1/$\{segment}