server:
  port: 8061

  servlet:
    context-path: /contamsvc

spring:
  application:
    name: contasvc

  zipkin:
    sender:
      type: web
    baseUrl: http://zipkinsrv:9411/

  sleuth:
    sampler:
      probability: 1.0

  data:
    mongodb:
      host: mongosrv
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: cartoes

ribbon:
  eureka:
    enabled: true

logging:
  file:
    name: '/mylogs/conta_elk.log'
  level:
    root: INFO
    org.pismo.cartoes: TRACE

eureka:
  instance:
    preferIpAddress: true
    hostname: contasrv
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekasrv:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
